name: Bug Report
description: Report a bug or issue with OpusGenie DI
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: OpusGenie DI Version
      description: What version of OpusGenie DI are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a component with '...'
        2. Register it with '...'
        3. Try to resolve '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: Minimal code example that reproduces the issue
      render: python
      placeholder: |
        from opusgenie_di import og_component, BaseComponent
        
        @og_component()
        class MyService(BaseComponent):
            pass
        
        # Code that demonstrates the issue...

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or stack traces
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.